version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "/libasynWebHook-PM/example-plugin/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/libasynWebHook-Nukkit/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/libasynWebHook-Nukkit/nukkit-example/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/libasynWebHook-WDPE/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/libasynWebHook-API/"
    schedule:
      interval: "daily"