--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/iAldrich23xX/libasynWeebhook-PM
build-by-default: true
branches:
- pmmp4
projects:
  libasynWeebHook-PM:
    path: ""
    model: virion
    type: library
...
