--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/iAldrich23xX/libasynWeebhook-PM
build-by-default: true
branches:
- master
projects:
  libasynWebHook:
    path: libasynDiscordWebhook-PM
    model: virion
    type: library
...
