name: Release Maven Projects

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Create Build
    if: "startsWith(github.event.head_commit.message, '[Release] ')"
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven

      - name: Build
        run: mvn clean package

      - name: Get Maven version
        run: |
          VERSION=$(mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: ${{ github.workspace }}/libasynDiscordWebHook-API/target/libasynDiscordWebHook-API-${{ env.VERSION }}.jar, ${{ github.workspace }}/libasynDiscordWebHook-Nukkit/target/libasynDiscordWebHook-Nukkit-${{ env.VERSION }}.jar, ${{ github.workspace }}/libasynDiscordWebHook-Nukkit/nukkit-example/target/nukkit-example-${{ env.VERSION }}.jar
          draft: false
          name: Release v${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "The artifacts are kept up to date with the branch release."
          commit: ${{ github.sha }}
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true